//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scoring_MGDPData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestaCompras
    {
        public string Tipo { get; set; }
        public string AreaSolicitante { get; set; }
        public string Contrato { get; set; }
        public string Proveedor { get; set; }
        public string Division { get; set; }
        public string Gerencia { get; set; }
        public string Usuario { get; set; }
        public string ContratoFechaInicio { get; set; }
        public string ContratoFechaFin { get; set; }
        public string DSC1 { get; set; }
        public string DSC2 { get; set; }
        public string DSC3 { get; set; }
        public string DSC4 { get; set; }
        public string DSC5 { get; set; }
        public string DSC6 { get; set; }
        public string DSS1 { get; set; }
        public string DSS2 { get; set; }
        public string CDS3 { get; set; }
        public string CALIDAD { get; set; }
        public string SERVICIO { get; set; }
        public Nullable<System.DateTime> PeriodoEncuestado { get; set; }
        public Nullable<System.DateTime> FechaDesde { get; set; }
        public Nullable<System.DateTime> FechaHasta { get; set; }
    }
}
