//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scoring_MGDPData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicionesMetricas
    {
        public Nullable<System.DateTime> FechaMedicion { get; set; }
        public Nullable<int> id_DefMetricas { get; set; }
        public Nullable<int> id_TiposProyectos { get; set; }
        public Nullable<double> ValorMedido { get; set; }
        public string Calculado { get; set; }
        public Nullable<double> Cump_Ratio { get; set; }
        public string Calcula_RatioSN { get; set; }
        public int id_Medicion_Metrica { get; set; }
    
        public virtual DefMetricas DefMetricas { get; set; }
        public virtual TiposProyectos TiposProyectos { get; set; }
    }
}
