//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scoring_MGDPData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metricas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Metricas()
        {
            this.DefMetricas = new HashSet<DefMetricas>();
        }
    
        public int id_Metrica { get; set; }
        public string SiglaMetrica { get; set; }
        public string DescripcionMet { get; set; }
        public Nullable<int> id_TipoMetrica { get; set; }
        public Nullable<int> id_UMedida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefMetricas> DefMetricas { get; set; }
        public virtual TiposMetricas TiposMetricas { get; set; }
        public virtual UnidadeDeMedidas UnidadeDeMedidas { get; set; }
    }
}
