//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scoring_MGDPData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposProyectos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TiposProyectos()
        {
            this.DefMetricas = new HashSet<DefMetricas>();
            this.MedicionesMetricas = new HashSet<MedicionesMetricas>();
        }
    
        public int id_TiposProyectos { get; set; }
        public string DescTipoProyecto { get; set; }
        public string SiglaTipoPry { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefMetricas> DefMetricas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicionesMetricas> MedicionesMetricas { get; set; }
    }
}
