//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scoring_MGDP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditorias
    {
        public int id_Auditoria { get; set; }
        public int id_Proyecto { get; set; }
        public string Pregunta { get; set; }
        public int Ciclo { get; set; }
        public System.DateTime FechaEjecucionCiclo { get; set; }
        public string ResultadoPregunta { get; set; }
        public string ResponsablePregunta { get; set; }
        public Nullable<int> id_Proveedor { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
    }
}
