//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scoring_MGDP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditorias_det_Pregunta
    {
        public int Proyecto { get; set; }
        public Nullable<int> Id_auditoría { get; set; }
        public string Área_de_proceso { get; set; }
        public string Pregunta { get; set; }
        public string C_Cumple_ { get; set; }
        public string Proveedor { get; set; }
        public string Feedback { get; set; }
        public string Normas { get; set; }
    }
}
