//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scoring_MGDP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditorias_datos
    {
        public int Proyecto { get; set; }
        public int Id_auditoría { get; set; }
        public string Área_proceso { get; set; }
        public string C__Complimiento { get; set; }
        public Nullable<int> Q_preguntas { get; set; }
        public Nullable<int> Q_preguntas_que_adhieren { get; set; }
        public Nullable<int> Q_preguntas_N_A { get; set; }
        public string Áreas_de_proceso { get; set; }
        public string Activos_a_revisar { get; set; }
        public Nullable<System.DateTime> F__planif_1__Revisión { get; set; }
        public Nullable<System.DateTime> F__planif_feedback { get; set; }
        public Nullable<System.DateTime> F__planif_2__Revisión { get; set; }
        public Nullable<System.DateTime> F__real_1__Revisión { get; set; }
        public Nullable<System.DateTime> F__real_feedback { get; set; }
        public Nullable<System.DateTime> F__real_2__Revisión { get; set; }
        public string Auditor { get; set; }
        public string Estado { get; set; }
        public string C_Fue_replanificada_ { get; set; }
    }
}
