//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scoring_MGDP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratoProv
    {
        public int id_Contrato { get; set; }
        public string NroContrato { get; set; }
        public Nullable<int> id_Proveedor { get; set; }
        public string Responsable { get; set; }
        public Nullable<double> MontoContrato { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
    }
}
