//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scoring_MGDP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encuestas
    {
        public int id_Encuesta { get; set; }
        public Nullable<int> Id_Proyecto { get; set; }
        public System.DateTime FechaEnvío { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string Pregunta { get; set; }
        public Nullable<int> Puntuacion { get; set; }
        public string Respuesta { get; set; }
        public string Encuesta_Tipo { get; set; }
        public string UsuarioEncuestado { get; set; }
        public string Estado { get; set; }
        public string AreaGestora { get; set; }
        public string NombreProveedor { get; set; }
        public Nullable<int> Id_Proveedor { get; set; }
        public Nullable<System.DateTime> Ult_Actualizacion { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
    }
}
