//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scoring_MGDP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scoring_Totales
    {
        public int id_Proveedor { get; set; }
        public string Proveedor { get; set; }
        public Nullable<System.DateTime> Periodo { get; set; }
        public Nullable<float> RMetricaGestion { get; set; }
        public Nullable<float> RMetricaContractual { get; set; }
        public Nullable<float> REncPry { get; set; }
        public Nullable<float> REncCompras { get; set; }
        public Nullable<float> RAuditorias { get; set; }
        public Nullable<float> PESO_METRICAGESTION { get; set; }
        public Nullable<float> PESO_METRICACONTRACTUAL { get; set; }
        public Nullable<float> PESO_METRICA { get; set; }
        public Nullable<float> PESO_ENCPRY { get; set; }
        public Nullable<float> PESO_ENCCOMPRAS { get; set; }
        public Nullable<float> PESO_ENCUESTAS { get; set; }
        public Nullable<float> PESO_AUDITORIAS { get; set; }
    }
}
