//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scoring_MGDP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scoring_Configuracion
    {
        public int id_MetricasScoring { get; set; }
        public string Metrica { get; set; }
        public Nullable<float> Peso { get; set; }
        public string Ambito { get; set; }
        public string Tipo { get; set; }
    }
}
